name: "Training Server #3"
duration: "10:00"
welcome_message: |
  Welcome to your last training, newbie. It’s time we introduce the last two important principles we currently know: Nodes and QPU (Quantum Processing Unit). Nodes are like a barrier on a tracing route (TR). On most servers one, or several, tracing programs will try to trace your AI via a TR. Nodes slow down a tracing program’s progress. In a game you could compare nodes to your health points. But beware, once the nodes on any TR run out, it’s game over.

  QPU on the other hand are used to execute more efficient tasks. While a Brute Force Attack without any QPU used might do 3 damage to a Security System, a BFA with 1 QPU used might do as much as 5 damage. Think of QPU as special points needed to do some actions that are often more powerful.

  We have also programmed a bot, so you can command AI yourself without a HFTD representative being ever present. That bot responds to a few commands. For instance:
  `~initiate server scan` will start the initial server scan. Try it now.

scan_result: |
  Let’s take a look at an initial scan:

  Port 1 (1 QPU):
  - Initial connect
  - Connect to port 2
  - Redirect up to 1 QPU from port 1 to port 2
  - Add 1 node to Trace Route 1
  - Download data

  Port 2 (0 QPU):
  - Connect to port 1
  - Brute Force Tracing System 1, 7 damage, costs 2 QPU linked to port 2
  - Link 1 QPU to port 2
  - Download data

  Nodes in Tracing Route 1: 1/5

  At the start of T3 Tracing System 1 becomes active, it requires 7 damage to be destroyed.
  At the end of T3 Tracing System 1 traces 1 node
  At the end of T5 Tracing System 1 traces 5 nodes

  At the start of T4 a Security Log is created in Port 1. If not changed before the start of T9, it will trace you, even if all AI are disconnected.

  As you can see there are some things going on. Tracing System 1 is fast but it isn't able to trace through many nodes at the start. Luckily we can add a node to Tracing Route 1 from Port 1, it’ll buy us some time. As you can see, the Brute Force attack from Port 2 is expensive, it costs 2 QPU, one of which we can redirect from Port 1. The other you’ll have to link up. Right now your computer can only link up 1 QPU to this server, but other servers might have a higher capacity and we are also working on some upgrades that you could buy that would make it so you can link more QPU to the target server. Keep earning those BitMint!

  Try and think of the solution to this server yourself for now or scroll down for the solution. Your goal is to download the data on both ports! And try and use the new bot commands to input your plan:

  If you think you found a solution type `~begin plan` to start inputting your plan. If you want to stop inputting stuff into your plan type `~end plan`.

  If you want to check your current plan simply type `~plan`

  If you want to run the eventual plan type `~run`.

  Let’s look at the Plan that will crack this server:

  T0: initial connect
  T1: Redirect 1 QPU from port 1 to port 2 <- To make sure we can Brute Force from there later
  T2: Add 1 node to TR 1 (cost 0 QPU) <- To buy us some time and prevent directly being traced
  T3: connect to port 2 <- We can’t Brute Force from anywhere else
  T4: Link 1 QPU to port 2 <- Because the Brute Force costs 2, but the server only has 1
  T5: Brute Force Tracing System 1 (cost 2 QPU, deals 7 damage) <- To destroy Tracing Sys 1
  T6: Download data from port 2 <- That’s our goal, part 1
  T7: Connect to port 1 <- There’s nothing left at port 2
  T8: Change Security Logs at port 1 <- To prevent being traced anyway
  T9: Download data from port 1 <- That’s our goal part 2
  T10: Disconnect

finished_timeout: |
  Oops! You ran out of time. Your QAI is now executing the last plan you submitted.

ports:
-
  id: 1
  qpu_start: 0
  qpu_max: 0
  actions:
  - initial connect
  - connect to port 2
  - redirect up to 1 QPU from port 1 to port 2
  - download data
  - edit data
-
  id: 2
  qpu_start: 0
  qpu_max: 0
  actions:
  - Connect to port 1
  - Brute Force Tracing System 1, 7 damage, costs 2 QPU linked to port 2
  - Link 1 QPU to port 2
  - Download data

threats:
-
  time: "1:00"
  description: "simple tracing program"
  start: 3
  health: 3
  trace_route: 1
  target: 1
-
  time: "2:00"
  description: "simple complete security log"
  start: 4
  security_log_port: 1
